services:
  app:
    image: gotodo
    build:
      args:
        - target=dev
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: admin
      DB_DATABASE: site
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:8.0
    platform: linux/x86_64
    container_name: site-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: site
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./volumes/test/db/data:/var/lib/mysql
      - ./volumes/test/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"